import "dotenv/config";
import esbuild from "esbuild";
import inlineWorkerPlugin from "esbuild-plugin-inline-worker";
import process from "process";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD FOR CLOUDSYNC
*/
`;

console.log(`esbuild version = ${esbuild.version}`);

const prod = process.argv[2] === "production";

esbuild
  .context({
    banner: {
      js: banner,
    },
    loader: {
      ".svg": "text",
    },
    entryPoints: ["./src/main.ts"],
    bundle: true,
    alias: {
      "node:url": "url",
    },
    external: [
      "obsidian",
      "electron",
      "fs",
      "tls",
      "net",
      "http",
      "https",
      "vm",
    ],
    inject: ["./esbuild.injecthelper.mjs"],
    format: "cjs",
    target: "es2022",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    minify: prod,
    outfile: "main.js",
    define: {
      global: "window",
      "process.env.NODE_DEBUG": `undefined`,
      "process.env.DEBUG": `undefined`,
      "globalThis.process.versions": `undefined`,
    },
    plugins: [inlineWorkerPlugin()],
  })
  .then((context) => {
    if (process.argv.includes("--watch")) {
      context.watch();
    } else {
      context.rebuild().then(() => {
        context.dispose();
      });
    }
  })
  .catch((err) => {
    console.error(err);
    process.exit(1);
  });
